version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/server
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/server
    expose:
      - "8050"
    command: "npm run dev"